# Generated by Django 2.1.3 on 2018-11-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0002_auto_20181111_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productresponse',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
