# Generated by Django 2.1.3 on 2018-11-21 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerceApp', '0003_auto_20181111_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eCommerceApp.Promotion'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount_percentage',
            field=models.FloatField(default=0),
        ),
    ]
